//! mylar3 tool surface.
//!
//! Endpoint registry: `mylar3.{list, detail, create, update, delete}` —
//! generated by `#[endpoint_resource]`.
//!
//! Detect + remediate:
//!   - `mylar3.status`           search reach, completed-download handling, stuck grabs, torrent wiring
//!   - `mylar3.configure`        fix settings drift through the web settings form (dry run by default)
//!   - `mylar3.backlog.process`  queue Mylar's post-processor over a completed-downloads folder (dry run by default)

use plugin_toolkit::prelude::*;

use crate::api::Mylar;
use crate::execute;
use crate::remediate::{self, BacklogProcess, ConfigureReport};
use crate::status::{self, StatusReport};

#[endpoint_resource(plugin = "mylar3")]
pub struct Mylar3Endpoint {
    pub name: String,
    #[secret]
    pub api_key: String,
    /// Web UI login, needed to read settings when Mylar's web UI uses basic auth.
    pub web_username: Option<String>,
    #[secret]
    pub web_password: Option<String>,
    pub enabled: bool,
}

pub async fn connect(name: &str) -> Result<Mylar> {
    let row = endpoint_db::require(name)?;
    let api_key = plugin_toolkit::secrets::resolve_scoped(
        "mylar3",
        name,
        "api_key",
        (!row.api_key.is_empty()).then_some(row.api_key.as_str()),
    )?;
    let web_auth = match row.web_username.filter(|u| !u.is_empty()) {
        Some(user) => {
            let pass = plugin_toolkit::secrets::resolve_scoped(
                "mylar3",
                name,
                "web_password",
                row.web_password.as_deref(),
            )?;
            Some((user, pass))
        }
        None => None,
    };
    let base_url = route::resolve_reachable(name, &row.routes, false).await?;
    Ok(Mylar::new(&base_url, &api_key, web_auth))
}

const DEFAULT_STUCK_HOURS: u32 = 24;

#[orca_struct(args)]
pub struct StatusArgs {
    /// Registered mylar3 endpoint name.
    #[arg(long)]
    pub name: String,
    /// A grab still at Snatched after this many hours counts as stuck.
    #[arg(long, default_value_t = DEFAULT_STUCK_HOURS)]
    #[serde(default = "default_stuck_hours")]
    pub stuck_hours: u32,
}

fn default_stuck_hours() -> u32 {
    DEFAULT_STUCK_HOURS
}

/// Detect drift that silently breaks comics: `usenet_retention` against the
/// oldest Wanted issue, completed-download handling, issues stuck at Snatched,
/// search delay, and torrent search without a configured client. Settings
/// Mylar will not hand over are reported as unknown, with the reason.
#[orca_tool(domain = "mylar3", verb = "status", role = "read")]
async fn mylar3_status(args: StatusArgs, _ctx: &ToolCtx) -> Result<StatusReport> {
    let m = connect(&args.name).await?;
    status::status(&args.name, &m, args.stuck_hours).await
}

#[orca_struct(args)]
pub struct ConfigureArgs {
    /// Registered mylar3 endpoint name.
    #[arg(long)]
    pub name: String,
    /// Days of usenet retention to advertise to indexers (newznab `maxage`).
    /// Match the shortest retention among your news providers.
    #[arg(long, default_value_t = remediate::DEFAULT_USENET_RETENTION)]
    #[serde(default = "default_usenet_retention")]
    pub usenet_retention: u32,
    /// Apply. Omitted, reports drift and changes nothing.
    #[arg(long)]
    #[serde(default)]
    pub execute: bool,
}

fn default_usenet_retention() -> u32 {
    remediate::DEFAULT_USENET_RETENTION
}

/// **Fix settings drift**: `usenet_retention` against the target, and
/// `nzb_downloader` when SABnzbd is set up but unused. Mylar's only settings
/// writer is its all-or-nothing web form, so `execute` re-posts every checkbox
/// and provider at its current value with the changes applied, then re-reads
/// and reports anything else that moved as `side_effects`. Without `execute`,
/// reports drift and changes nothing.
#[orca_tool(
    domain = "mylar3",
    verb = "configure",
    role = "admin",
    execute_gated = false
)]
async fn mylar3_configure(args: ConfigureArgs, ctx: &ToolCtx) -> Result<ConfigureReport> {
    const TOOL: &str = "mylar3.configure";
    execute::require_admin(TOOL, ctx)?;
    let m = connect(&args.name).await?;
    remediate::configure(&args.name, &m, args.usenet_retention, args.execute).await
}

#[orca_struct(args)]
pub struct BacklogArgs {
    /// Registered mylar3 endpoint name.
    #[arg(long)]
    pub name: String,
    /// Completed-downloads folder as Mylar's container sees it, e.g.
    /// `/downloads/completed/comics`.
    #[arg(long)]
    pub folder: String,
    /// Threshold for the stuck-at-Snatched count reported alongside.
    #[arg(long, default_value_t = DEFAULT_STUCK_HOURS)]
    #[serde(default = "default_stuck_hours")]
    pub stuck_hours: u32,
    /// Apply. Omitted, reports the stuck count and queues nothing.
    #[arg(long)]
    #[serde(default)]
    pub execute: bool,
}

/// **Import the backlog**: queue Mylar's post-processor over `folder`
/// (`forceProcess`, `Manual Run`), which matches every file there against the
/// watchlist and moves hits into the library. Without `execute`, reports how
/// many issues are stuck at Snatched and queues nothing.
#[orca_tool(
    domain = "mylar3",
    verb = "backlog.process",
    role = "admin",
    execute_gated = false
)]
async fn mylar3_backlog_process(args: BacklogArgs, ctx: &ToolCtx) -> Result<BacklogProcess> {
    const TOOL: &str = "mylar3.backlog.process";
    execute::require_admin(TOOL, ctx)?;
    let m = connect(&args.name).await?;
    remediate::process_backlog(&args.name, &m, &args.folder, args.stuck_hours, args.execute).await
}
